### ISSUE TITLE
1st Gen Sensibo Pods

### ISSUE THREAD

**Issue by Cloudore** [wailuen/homebridge-sensibo-sky#1]
Since we're using the same API, Can I use this plug-in with my 1st gen pods? the error handling is a nice touch that I'd like. If not maybe you could do a pull request with your improvements on the homebridge-sensibo plug in?

Thanks !

**Comment by wailuen** [comment]
Hi, I wanted to merge my changes to the original and lost the patient on learning how to do all the pull and stuff. Will tried that when i have the time. 

Since the API is the same, i believe this plug-in will work for the 1st gen pods as well. I only have the sensibo sky and thus only can test with it.

**Comment by Cloudore** [comment]
It works with 1st Gen Sensibo, Confirmed!

Only problem is Fan takes a little long to update in the Home app once you manipulate it, and until it updates (to one of the three states: low medium high) you can't manipulate it again, it won't register your movements, it'll just bounce back to the first manipulation when it finally updates, other than that, it works great, Thanks!

P.S: Is there something I could change to just disable the Fan service? leave it high as default and be able to manipulate it only on the Sensible App

**Comment by wailuen** [comment]
This has to do with the way Sensibo server respond to update command. It bounds back to the original level if the update cmd failed. Even in the event when the update is successful, the status are only refreshed at 60s interval to avoid Sensibo server refusing connection. Let me shorten the update interval to reflect better status so that you will not feel that the update did not goes through.

**Comment by Cloudore** [comment]
Thanks for the follow up, by the way, pdlove doesn't have the Sensibo hardware and is looking for someone to take over the plugin, you could do that, this one works great

**Comment by wailuen** [comment]
Somehow, that one does not work for me. Somehow, it takes a long time to update only 1 of 3 sky pods at any time. That is why I forked out to troubleshoot and enhance for my own use. 

Best Regards,

蒋玮伦
CHEONG Wai Luen

**Comment by wailuen** [comment]
Updated to fix more reliable fan speed update. It reverts back to original level when update failed. Also introduce 2 new paramters:
timeLapse - to determine how frequent to check Sensibo for status
ai - to auto manipulate the fan speed to achieve target temperature faster. With a >5% in temperature, set speed to 100% and gradually reduce to auto once it hit the target temperature.
